import {
  CueCardSchema,
  VideoLessonSchema,
  type CueCard,
  type VideoLesson,
} from "./schemas";

// DRAFT LANGUAGE CONTENT — requires review by a qualified Thai language editor.
const draftLessons: VideoLesson[] = [
  {
    id: "coffee-order",
    order: 1,
    title: "Ordering a coffee",
    objective: "Ask for one drink and respond naturally to a short follow-up.",
    description: "A quiet counter exchange with three high-frequency phrases.",
    contentStatus: "draft",
    media: {
      videoSrc: "/lessons/coffee-order/intro.mp4",
      posterSrc: "/lessons/coffee-order/poster.jpg",
      captionsSrc: "/lessons/coffee-order/captions.vtt",
      durationSeconds: 26,
      availability: "draft-unavailable",
      fallbackMessage: "The lesson notes are ready. The reviewed clip and captions will be added when licensed media arrives.",
    },
    transcript: [
      {
        id: "coffee-1",
        startSeconds: 2.1,
        endSeconds: 5.8,
        speaker: "Customer",
        thai: "ขอกาแฟเย็นหนึ่งแก้วครับ",
        romanization: "khǎaw gaa-fɛɛ yen nʉ̀ng gɛ̂ɛo khráp",
        naturalEnglish: "One iced coffee, please.",
        contextNote: "ขอ makes a direct request sound natural. ครับ is used here by a male speaker.",
        verificationStatus: "draft",
      },
      {
        id: "coffee-2",
        startSeconds: 6.2,
        endSeconds: 8.6,
        speaker: "Server",
        thai: "หวานไหมคะ",
        romanization: "wǎan mái khá",
        naturalEnglish: "Would you like it sweet?",
        literalNote: "Sweet + question particle?",
        verificationStatus: "draft",
      },
      {
        id: "coffee-3",
        startSeconds: 9.1,
        endSeconds: 11.9,
        speaker: "Customer",
        thai: "ไม่หวานครับ",
        romanization: "mâi wǎan khráp",
        naturalEnglish: "Not sweet, please.",
        contextNote: "A compact, common preference response.",
        verificationStatus: "draft",
      },
    ],
    cueCardIds: ["request-one", "sweet-question", "not-sweet"],
    quizBank: [
      {
        id: "coffee-q1",
        itemId: "request-one",
        prompt: "Which phrase asks for one iced coffee?",
        choices: ["ขอกาแฟเย็นหนึ่งแก้วครับ", "หวานไหมคะ", "ไม่หวานครับ"],
        correctIndex: 0,
        explanation: "ขอ introduces the request; หนึ่งแก้ว gives the quantity and classifier.",
      },
      {
        id: "coffee-q2",
        itemId: "not-sweet",
        prompt: "The server asks หวานไหมคะ. Choose a concise reply for ‘not sweet.’",
        choices: ["หวานไหมคะ", "ไม่หวานครับ", "หนึ่งแก้วครับ"],
        correctIndex: 1,
        explanation: "ไม่ negates หวาน, giving ‘not sweet.’",
      },
    ],
  },
  {
    id: "market-price",
    order: 2,
    title: "Asking the price",
    objective: "Ask what something costs and catch the number in reply.",
    description: "A short exchange at a neighborhood market stall.",
    contentStatus: "draft",
    media: {
      videoSrc: "/lessons/market-price/intro.mp4",
      posterSrc: "/lessons/market-price/poster.jpg",
      captionsSrc: "/lessons/market-price/captions.vtt",
      durationSeconds: 22,
      availability: "draft-unavailable",
      fallbackMessage: "This future lesson is waiting for reviewed language and licensed media.",
    },
    transcript: [],
    cueCardIds: [],
    quizBank: [],
  },
  {
    id: "ride-destination",
    order: 3,
    title: "Confirming a destination",
    objective: "Name a destination and confirm that the driver understood.",
    description: "The first seconds of a practical ride conversation.",
    contentStatus: "draft",
    media: {
      videoSrc: "/lessons/ride-destination/intro.mp4",
      posterSrc: "/lessons/ride-destination/poster.jpg",
      captionsSrc: "/lessons/ride-destination/captions.vtt",
      durationSeconds: 24,
      availability: "draft-unavailable",
      fallbackMessage: "This future lesson is waiting for reviewed language and licensed media.",
    },
    transcript: [],
    cueCardIds: [],
    quizBank: [],
  },
];

const draftCueCards: CueCard[] = [
  {
    id: "request-one",
    lessonId: "coffee-order",
    thai: "ขอ…หนึ่ง…ครับ/ค่ะ",
    romanization: "khǎaw… nʉ̀ng… khráp/khâ",
    naturalMeaning: "Could I have one… please?",
    usage: "A flexible request frame. Put the item after ขอ and its classifier after หนึ่ง.",
    transcriptReferences: ["coffee-1"],
    verificationStatus: "draft",
  },
  {
    id: "sweet-question",
    lessonId: "coffee-order",
    thai: "หวานไหมคะ",
    romanization: "wǎan mái khá",
    naturalMeaning: "Would you like it sweet?",
    usage: "A yes/no question about sweetness; often heard when ordering drinks.",
    transcriptReferences: ["coffee-2"],
    verificationStatus: "draft",
  },
  {
    id: "not-sweet",
    lessonId: "coffee-order",
    thai: "ไม่หวานครับ/ค่ะ",
    romanization: "mâi wǎan khráp/khâ",
    naturalMeaning: "Not sweet, please.",
    usage: "A brief preference response. Choose the final polite particle appropriate to your speech.",
    transcriptReferences: ["coffee-3"],
    verificationStatus: "draft",
  },
];

export const lessons = VideoLessonSchema.array().parse(draftLessons);
export const cueCards = CueCardSchema.array().parse(draftCueCards);
export const firstLesson = lessons[0];
