const $=id=>document.getElementById(id);let data,index=0,dragging=null,contextEnd=0;
const video=$("video"),audio=$("audio"),canvas=$("waveform"),startInput=$("start"),endInput=$("end");
async function load(keep){data=await fetch("/api/data").then(r=>r.json());if(keep)index=Math.min(index,data.clips.length-1);$("title").textContent=data.lesson.title;render()}
function clip(){return data.clips[index]}
function approved(c){return c.boundaryMethod?.start==="override"&&!(c.warnings||[]).some(w=>w.includes("stale")||w.includes("legacy"))}
function render(){const c=clip(),concept=Math.floor(index/2)+1,concepts=Math.ceil(data.clips.length/2),part=index%2+1,next=data.clips[(index+1)%data.clips.length],candidate=c.candidates?.[0],seedStart=c.start??c.rawStart??candidate?.start??0,seedEnd=c.end??c.rawEnd??candidate?.end??Math.min(data.duration,seedStart+1);$("position").textContent=`Concept ${concept} / ${concepts} · clip ${part} / 2`;$("language").textContent=`${c.language} clip only`;$("text").textContent=c.text;$("counterpart").textContent=`Paired ${c.language==="thai"?"English":"Thai"} clip: ${c.counterpart}`;$("next").textContent=`Next: ${next.language} ${next.text} →`;startInput.value=seedStart.toFixed(3);endInput.value=seedEnd.toFixed(3);startInput.max=endInput.max=data.duration;const warnings=c.warnings||[];$("status").innerHTML=`<span class="badge ${approved(c)?"good":""}">${approved(c)?"approved":c.status}</span>${warnings.map(w=>`<span class="badge warning">${w}</span>`).join("")}`;$("progress").textContent=`${data.clips.filter(approved).length} of ${data.clips.length} language clips approved`;$("message").textContent=c.status==="unmatched"?"No safe automatic match. Locate the phrase in the video, set both handles, then play and approve the exact cut.":c.status==="ambiguous"?"Multiple possible matches were found. Confirm this occurrence against the video before approving.":"";draw()}
function values(){return{start:Number(startInput.value),end:Number(endInput.value)}}
function setBoundary(which,value){const current=values();const bounded=which==="start"?Math.max(0,Math.min(value,current.end-.01)):Math.min(data.duration,Math.max(value,current.start+.01));(which==="start"?startInput:endInput).value=bounded.toFixed(3);draw()}
function draw(){if(!data)return;const ratio=devicePixelRatio||1;const box=canvas.getBoundingClientRect();canvas.width=Math.max(1,box.width*ratio);canvas.height=180*ratio;const ctx=canvas.getContext("2d");ctx.scale(ratio,ratio);const w=box.width,h=180;ctx.clearRect(0,0,w,h);ctx.fillStyle="#aab5af";const step=w/data.peaks.length;data.peaks.forEach((p,i)=>{const height=Math.max(1,p*(h-30));ctx.fillRect(i*step,(h-height)/2,Math.max(1,step),height)});const c=clip(),v=values();const x=t=>t/data.duration*w;ctx.fillStyle="#e2a33b55";if(c.rawStart!=null)ctx.fillRect(x(c.rawStart),0,Math.max(2,x(c.rawEnd)-x(c.rawStart)),h);ctx.fillStyle="#617eaa55";if(c.protectedStart!=null)ctx.fillRect(x(c.protectedStart),0,Math.max(2,x(c.protectedEnd)-x(c.protectedStart)),h);ctx.fillStyle="#39715d20";ctx.fillRect(x(v.start),0,Math.max(2,x(v.end)-x(v.start)),h);ctx.strokeStyle="#39715d";ctx.lineWidth=3;[v.start,v.end].forEach(t=>{ctx.beginPath();ctx.moveTo(x(t),0);ctx.lineTo(x(t),h);ctx.stroke()});ctx.fillStyle="#18201d";ctx.font="11px system-ui";ctx.fillText(`${v.start.toFixed(3)}s`,Math.min(w-55,x(v.start)+5),15);ctx.fillText(`${v.end.toFixed(3)}s`,Math.max(3,x(v.end)-52),h-7)}
function play(src){audio.src=`${src}${src.includes("?")?"&":"?"}v=${Date.now()}`;audio.loop=$("loop").checked;audio.play()}
function playPreview(){const v=values();if(v.start<0||v.end<=v.start||v.end>data.duration){$("message").textContent="The range must be ordered and inside the video.";return}play(`/api/preview?start=${v.start}&end=${v.end}`)}
$("previous").onclick=()=>{index=(index-1+data.clips.length)%data.clips.length;render()};$("next").onclick=()=>{index=(index+1)%data.clips.length;render()};
$("preview").onclick=playPreview;$("current").onclick=()=>play(`/audio/current/${clip().file}`);$("baseline").onclick=()=>play(`/audio/baseline/${clip().file}`);
$("context").onclick=()=>{const v=values();video.currentTime=Math.max(0,v.start-1);contextEnd=Math.min(data.duration,v.end+1);video.play()};video.addEventListener("timeupdate",()=>{if(contextEnd&&video.currentTime>=contextEnd){video.pause();contextEnd=0}});
[startInput,endInput].forEach(input=>input.addEventListener("input",draw));document.querySelectorAll("[data-nudge]").forEach(button=>button.onclick=()=>{const [which,amount]=button.dataset.nudge.split(":");const input=which==="start"?startInput:endInput;setBoundary(which,Number(input.value)+Number(amount))});
$("approve").onclick=async()=>{const v=values(),c=clip();if(v.start<0||v.end<=v.start||v.end>data.duration){$("message").textContent="The range must be ordered and inside the video.";return}$("approve").disabled=true;$("message").textContent="Saving and regenerating this clip…";const response=await fetch("/api/approve",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cardId:c.cardId,language:c.language,...v})});const result=await response.json();$("approve").disabled=false;if(!response.ok){$("message").textContent=result.error||"Save failed";return}data=result;render();$("message").textContent="Approved and regenerated."};
function pointerTime(event){const box=canvas.getBoundingClientRect();return Math.max(0,Math.min(data.duration,(event.clientX-box.left)/box.width*data.duration))}canvas.addEventListener("pointerdown",event=>{const t=pointerTime(event),v=values();dragging=Math.abs(t-v.start)<Math.abs(t-v.end)?"start":"end";canvas.setPointerCapture(event.pointerId)});canvas.addEventListener("pointermove",event=>{if(dragging)setBoundary(dragging,pointerTime(event))});canvas.addEventListener("pointerup",()=>dragging=null);
addEventListener("resize",draw);addEventListener("keydown",event=>{if(event.target instanceof HTMLInputElement)return;if(event.code==="Space"){event.preventDefault();playPreview()}else if(event.key==="ArrowLeft")$("previous").click();else if(event.key==="ArrowRight")$("next").click();else if(event.key.toLowerCase()==="a")$("approve").click()});load();
