import type { Course, Exercise, Lesson } from "@/src/domain/types";

const exercise = (value: Exercise): Exercise => value;

const lessons: Lesson[] = [
  {
    id: "hello-there",
    unitId: "warm-welcome",
    title: "Hello there",
    eyebrow: "First words",
    description: "Say hello and make a warm first impression.",
    icon: "Sparkles",
    xp: 12,
    exercises: [
      exercise({
        id: "hello-listen",
        type: "listen-choice",
        instruction: "Listen and choose what you hear",
        prompt: "Which phrase did Nok say?",
        thai: "สวัสดี",
        romanization: "sà-wàt-dee",
        audioRef: "tts:สวัสดี",
        choices: [
          { id: "a", label: "Hello", thai: "สวัสดี" },
          { id: "b", label: "Thank you", thai: "ขอบคุณ" },
          { id: "c", label: "Goodbye", thai: "ลาก่อน" },
        ],
        correctAnswer: "a",
        hint: "You will hear this one everywhere in Thailand.",
        explanation: "สวัสดี is the standard friendly greeting.",
      }),
      exercise({
        id: "hello-meaning",
        type: "thai-to-english",
        instruction: "Choose the meaning",
        prompt: "สวัสดี means…",
        thai: "สวัสดี",
        romanization: "sà-wàt-dee",
        choices: [
          { id: "hello", label: "Hello" },
          { id: "hungry", label: "I’m hungry" },
          { id: "okay", label: "It’s okay" },
        ],
        correctAnswer: "hello",
        explanation: "Add ครับ (men) or ค่ะ (women) to sound extra polite.",
      }),
      exercise({
        id: "hello-order",
        type: "word-order",
        instruction: "Build the phrase",
        prompt: "Hello (said by a man)",
        tokens: ["ครับ", "สวัสดี"],
        correctAnswer: ["สวัสดี", "ครับ"],
        explanation: "ครับ (kráp) is a polite particle commonly used by men.",
      }),
    ],
  },
  {
    id: "polite-particles",
    unitId: "warm-welcome",
    title: "Sound polite",
    eyebrow: "Everyday Thai",
    description: "Use the tiny words that make a big difference.",
    icon: "Heart",
    xp: 14,
    exercises: [
      exercise({
        id: "polite-choice",
        type: "conversation",
        instruction: "Choose the best reply",
        prompt: "Your neighbor says สวัสดีค่ะ. What do you say back?",
        choices: [
          { id: "a", label: "สวัสดีครับ", romanization: "sà-wàt-dee kráp" },
          { id: "b", label: "ไม่เอา", romanization: "mâi ao" },
          { id: "c", label: "เผ็ดมาก", romanization: "pèt mâak" },
        ],
        correctAnswer: "a",
        explanation: "Mirror the greeting and use your polite particle.",
      }),
      exercise({
        id: "polite-match",
        type: "matching",
        instruction: "Match the pairs",
        prompt: "Pair each Thai phrase with its meaning",
        pairs: [
          { id: "hello", left: "สวัสดี", right: "Hello" },
          { id: "thanks", left: "ขอบคุณ", right: "Thank you" },
          { id: "yes", left: "ใช่", right: "Yes" },
        ],
        correctAnswer: ["hello", "thanks", "yes"],
      }),
      exercise({
        id: "polite-fill",
        type: "fill-blank",
        instruction: "Complete the phrase",
        prompt: "สวัสดี ___",
        romanization: "sà-wàt-dee ___",
        correctAnswer: "ครับ",
        acceptedAnswers: ["ครับ", "ค่ะ"],
        hint: "Use the polite particle that feels right for you.",
      }),
    ],
  },
  {
    id: "thank-you",
    unitId: "warm-welcome",
    title: "Thanks a lot",
    eyebrow: "Good manners",
    description: "Give thanks and answer graciously.",
    icon: "Gift",
    xp: 15,
    exercises: [
      exercise({
        id: "thanks-meaning",
        type: "english-to-thai",
        instruction: "Choose the Thai phrase",
        prompt: "Thank you",
        choices: [
          { id: "a", label: "ขอบคุณ", romanization: "kòp-kun" },
          { id: "b", label: "ขอโทษ", romanization: "kŏr-tôht" },
          { id: "c", label: "ไม่เป็นไร", romanization: "mâi bpen rai" },
        ],
        correctAnswer: "a",
        explanation: "ขอบคุณ is the everyday way to say thank you.",
      }),
      exercise({
        id: "thanks-listen",
        type: "listen-choice",
        instruction: "Listen and choose",
        prompt: "What does this phrase mean?",
        thai: "ไม่เป็นไร",
        romanization: "mâi bpen rai",
        audioRef: "tts:ไม่เป็นไร",
        choices: [
          { id: "a", label: "No worries" },
          { id: "b", label: "See you tomorrow" },
          { id: "c", label: "Two waters, please" },
        ],
        correctAnswer: "a",
      }),
      exercise({
        id: "thanks-speak",
        type: "speaking",
        instruction: "Say it out loud",
        prompt: "Say ‘thank you’ in Thai",
        thai: "ขอบคุณ",
        romanization: "kòp-kun",
        audioRef: "tts:ขอบคุณ",
        correctAnswer: "ขอบคุณ",
        acceptedAnswers: ["ขอบคุณ", "ขอบคุณครับ", "ขอบคุณค่ะ"],
        explanation: "Nice! The final consonants are soft and quick.",
      }),
    ],
  },
  {
    id: "street-food",
    unitId: "tasty-thai",
    title: "Street food",
    eyebrow: "Order with confidence",
    description: "Ask for favorites at a food stall.",
    icon: "Soup",
    xp: 16,
    exercises: [
      exercise({
        id: "food-choice",
        type: "thai-to-english",
        instruction: "Choose the meaning",
        prompt: "ผัดไทย means…",
        thai: "ผัดไทย",
        romanization: "pàt tai",
        choices: [
          { id: "a", label: "Pad Thai" },
          { id: "b", label: "Mango" },
          { id: "c", label: "Iced coffee" },
        ],
        correctAnswer: "a",
      }),
      exercise({
        id: "food-order",
        type: "word-order",
        instruction: "Build the phrase",
        prompt: "One Pad Thai, please",
        tokens: ["ครับ", "หนึ่ง", "ผัดไทย", "จาน"],
        correctAnswer: ["ผัดไทย", "หนึ่ง", "จาน", "ครับ"],
        hint: "Thai classifiers come after the number here.",
      }),
      exercise({
        id: "food-conversation",
        type: "conversation",
        instruction: "Respond at the stall",
        prompt: "The cook asks: เอาเผ็ดไหม — Do you want it spicy?",
        choices: [
          {
            id: "a",
            label: "เผ็ดนิดหน่อย",
            romanization: "pèt nít nòi",
            thai: "A little spicy",
          },
          {
            id: "b",
            label: "สวัสดี",
            romanization: "sà-wàt-dee",
            thai: "Hello",
          },
          {
            id: "c",
            label: "เจอกันพรุ่งนี้",
            romanization: "jer gan prûng-née",
            thai: "See you tomorrow",
          },
        ],
        correctAnswer: "a",
      }),
    ],
  },
  {
    id: "not-too-spicy",
    unitId: "tasty-thai",
    title: "Not too spicy",
    eyebrow: "Personal taste",
    description: "Tell the cook exactly how you like it.",
    icon: "Flame",
    xp: 16,
    exercises: [
      exercise({
        id: "spicy-fill",
        type: "fill-blank",
        instruction: "Complete the request",
        prompt: "ไม่ ___ ครับ — Not spicy, please",
        correctAnswer: "เผ็ด",
        acceptedAnswers: ["เผ็ด"],
        hint: "The missing word sounds like pèt.",
      }),
      exercise({
        id: "spicy-listen",
        type: "listen-choice",
        instruction: "Listen for the spice level",
        prompt: "What did Nok ask for?",
        thai: "เผ็ดนิดหน่อย",
        romanization: "pèt nít nòi",
        audioRef: "tts:เผ็ดนิดหน่อย",
        choices: [
          { id: "a", label: "A little spicy" },
          { id: "b", label: "Very spicy" },
          { id: "c", label: "Not spicy" },
        ],
        correctAnswer: "a",
      }),
      exercise({
        id: "spicy-speak",
        type: "speaking",
        instruction: "Try the phrase",
        prompt: "Ask for ‘not spicy’",
        thai: "ไม่เผ็ด",
        romanization: "mâi pèt",
        audioRef: "tts:ไม่เผ็ด",
        correctAnswer: "ไม่เผ็ด",
        acceptedAnswers: ["ไม่เผ็ด", "ไม่เผ็ดครับ", "ไม่เผ็ดค่ะ"],
      }),
    ],
  },
  {
    id: "the-bill",
    unitId: "tasty-thai",
    title: "The bill, please",
    eyebrow: "Wrap it up",
    description: "Pay, compliment the food, and say goodbye.",
    icon: "ReceiptText",
    xp: 18,
    exercises: [
      exercise({
        id: "bill-order",
        type: "word-order",
        instruction: "Build the phrase",
        prompt: "The bill, please",
        tokens: ["ครับ", "ด้วย", "เช็คบิล"],
        correctAnswer: ["เช็คบิล", "ด้วย", "ครับ"],
      }),
      exercise({
        id: "bill-choice",
        type: "conversation",
        instruction: "Choose a natural reply",
        prompt: "The server asks: อร่อยไหม — Was it delicious?",
        choices: [
          {
            id: "a",
            label: "อร่อยมาก!",
            romanization: "à-ròi mâak",
            thai: "Very delicious!",
          },
          {
            id: "b",
            label: "ไม่รู้",
            romanization: "mâi róo",
            thai: "I don’t know",
          },
          {
            id: "c",
            label: "ห้องน้ำ",
            romanization: "hông náam",
            thai: "Bathroom",
          },
        ],
        correctAnswer: "a",
      }),
      exercise({
        id: "bill-review",
        type: "mistake-review",
        instruction: "Quick review",
        prompt: "How do you say ‘no worries’?",
        choices: [
          { id: "a", label: "ไม่เป็นไร", romanization: "mâi bpen rai" },
          { id: "b", label: "ขอบคุณ", romanization: "kòp-kun" },
          { id: "c", label: "เช็คบิล", romanization: "chék bin" },
        ],
        correctAnswer: "a",
        explanation: "ไม่เป็นไร is a wonderfully flexible Thai phrase.",
      }),
    ],
  },
];

export const course: Course = {
  id: "spoken-thai-starter",
  title: "Conversational Thai",
  lessons: Object.fromEntries(lessons.map((lesson) => [lesson.id, lesson])),
  units: [
    {
      id: "warm-welcome",
      number: 1,
      title: "A warm welcome",
      description: "Greet people and sound naturally polite.",
      color: "coral",
      nodes: [
        {
          id: "n-hello",
          type: "lesson",
          title: "Hello there",
          lessonId: "hello-there",
        },
        {
          id: "n-polite",
          type: "lesson",
          title: "Sound polite",
          lessonId: "polite-particles",
        },
        {
          id: "n-thanks",
          type: "lesson",
          title: "Thanks a lot",
          lessonId: "thank-you",
        },
        { id: "n-checkpoint", type: "checkpoint", title: "Welcome checkpoint" },
      ],
    },
    {
      id: "tasty-thai",
      number: 2,
      title: "Tasty Thai",
      description: "Order a meal just the way you like it.",
      color: "teal",
      nodes: [
        {
          id: "n-food",
          type: "lesson",
          title: "Street food",
          lessonId: "street-food",
        },
        {
          id: "n-spicy",
          type: "lesson",
          title: "Not too spicy",
          lessonId: "not-too-spicy",
        },
        {
          id: "n-bill",
          type: "lesson",
          title: "The bill, please",
          lessonId: "the-bill",
        },
        { id: "n-review", type: "review", title: "Tasty Thai review" },
      ],
    },
  ],
};

export const orderedLessonIds = course.units.flatMap((unit) =>
  unit.nodes.flatMap((node) => (node.lessonId ? [node.lessonId] : [])),
);

export const findNextLessonId = (completed: string[]) =>
  orderedLessonIds.find((id) => !completed.includes(id)) ?? orderedLessonIds[0];
